#!/usr/bin/env python3
"""
Environment Setup Script for GSR Automation

This script helps users set up their .env file with the required credentials.
It provides a secure way to input sensitive information and validates the setup.
"""

import os
import getpass
from pathlib import Path


def create_env_file():
    """Create .env file with user input"""
    print("🔐 GSR Automation Environment Setup")
    print("=" * 50)
    print("This script will help you create a .env file with your credentials.")
    print("Your credentials will be stored locally and never shared.\n")
    
    # Check if .env already exists
    env_path = Path(".env")
    if env_path.exists():
        response = input("⚠️  .env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Setup cancelled.")
            return
    
    # Collect credentials
    credentials = {}
    
    print("\n📡 17Track API Configuration:")
    credentials['SEVENTEEN_TRACK_API_TOKEN'] = getpass.getpass("Enter your 17Track API token: ")
    
    print("\n📦 TrackingMore API Configuration:")
    credentials['TRACKINGMORE_API_KEY'] = getpass.getpass("Enter your TrackingMore API key: ")
    
    print("\n🗄️  ClickHouse Database Configuration:")
    credentials['CLICKHOUSE_HOST'] = input("Enter ClickHouse host: ")
    credentials['CLICKHOUSE_PORT'] = input("Enter ClickHouse port (default 9440): ") or "9440"
    credentials['CLICKHOUSE_USERNAME'] = input("Enter ClickHouse username: ")
    credentials['CLICKHOUSE_PASSWORD'] = getpass.getpass("Enter ClickHouse password: ")
    credentials['CLICKHOUSE_DATABASE'] = input("Enter ClickHouse database name: ")
    credentials['CLICKHOUSE_SECURE'] = input("Use SSL for ClickHouse? (Y/n): ").lower() != 'n'
    
    # Create .env content
    env_content = """# GSR Automation Environment Variables
# Generated by setup_env.py

# 17Track API Configuration
SEVENTEEN_TRACK_API_TOKEN={SEVENTEEN_TRACK_API_TOKEN}
SEVENTEEN_TRACK_API_URL=https://api.17track.net/track/v2.4/gettrackinfo
SEVENTEEN_TRACK_REGISTER_URL=https://api.17track.net/track/v2.2/register
SEVENTEEN_TRACK_DEFAULT_CARRIER_CODE=100002

# TrackingMore API Configuration
TRACKINGMORE_API_KEY={TRACKINGMORE_API_KEY}

# ClickHouse Database Configuration
CLICKHOUSE_HOST={CLICKHOUSE_HOST}
CLICKHOUSE_PORT={CLICKHOUSE_PORT}
CLICKHOUSE_USERNAME={CLICKHOUSE_USERNAME}
CLICKHOUSE_PASSWORD={CLICKHOUSE_PASSWORD}
CLICKHOUSE_DATABASE={CLICKHOUSE_DATABASE}
CLICKHOUSE_SECURE={CLICKHOUSE_SECURE}

# DLT Pipeline Configuration
DLT_WRITE_DISPOSITION=append
DLT_CLICKHOUSE_BATCH_SIZE=50000
DLT_CLICKHOUSE_WINDOW_SECONDS=3600
DLT_INVOICE_CUTOFF_DAYS=30
DLT_FORCE_FULL_LOAD=false

# Application Configuration
BATCH_SIZE=40
API_DELAY=1.0
DUCKDB_PATH=carrier_invoice_extraction.duckdb
OUTPUT_DIR=data/output
""".format(
        SEVENTEEN_TRACK_API_TOKEN=credentials['SEVENTEEN_TRACK_API_TOKEN'],
        TRACKINGMORE_API_KEY=credentials['TRACKINGMORE_API_KEY'],
        CLICKHOUSE_HOST=credentials['CLICKHOUSE_HOST'],
        CLICKHOUSE_PORT=credentials['CLICKHOUSE_PORT'],
        CLICKHOUSE_USERNAME=credentials['CLICKHOUSE_USERNAME'],
        CLICKHOUSE_PASSWORD=credentials['CLICKHOUSE_PASSWORD'],
        CLICKHOUSE_DATABASE=credentials['CLICKHOUSE_DATABASE'],
        CLICKHOUSE_SECURE=str(credentials['CLICKHOUSE_SECURE']).lower()
    )
    
    # Write .env file
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        # Set secure permissions (Unix-like systems)
        if os.name != 'nt':  # Not Windows
            os.chmod('.env', 0o600)
        
        print("\n✅ .env file created successfully!")
        print("🔒 File permissions set to secure (owner read/write only)")
        print("\n📋 Next steps:")
        print("1. Verify your credentials are correct")
        print("2. Test the connection with: poetry run python tests/test_clickhouse_connection.py")
        print("3. Run the pipeline with: poetry run python src/src/dlt_pipeline_examples.py")
        
    except Exception as e:
        print(f"\n❌ Error creating .env file: {e}")
        return


def validate_env():
    """Validate existing .env file"""
    print("🔍 Validating .env file...")
    
    if not Path('.env').exists():
        print("❌ .env file not found. Run this script to create one.")
        return False
    
    from dotenv import load_dotenv
    load_dotenv()
    
    required_vars = [
        'SEVENTEEN_TRACK_API_TOKEN',
        'TRACKINGMORE_API_KEY',
        'CLICKHOUSE_HOST',
        'CLICKHOUSE_USERNAME',
        'CLICKHOUSE_PASSWORD',
        'CLICKHOUSE_DATABASE'
    ]
    
    missing_vars = []
    for var in required_vars:
        if not os.getenv(var):
            missing_vars.append(var)
    
    if missing_vars:
        print(f"❌ Missing required variables: {', '.join(missing_vars)}")
        return False
    
    print("✅ All required environment variables are set!")
    return True


def main():
    """Main function"""
    if len(os.sys.argv) > 1 and os.sys.argv[1] == 'validate':
        validate_env()
    else:
        create_env_file()


if __name__ == "__main__":
    main()
